#!/usr/bin/env python3
"""Build scout.db from the seed below (one row per site, verified=0)."""
import json, os, sqlite3

DB = "scout.db"
SRC = "Ontario Parks campground maps (ranges) - UNVERIFIED, expand & check"

F = dict(
    elec="Electrical sites", showers="Showers", flush="Flush toilets", vault="Vault toilets",
    laundry="Laundry", water="Water taps", dump="Trailer dump station", firewood="Firewood",
    store="Park store", beaches="Beaches", boat="Boat launch", canoe="Canoe launches",
    rentals="Canoe/kayak rentals", pfd="PFD loan", trails="Hiking trails", bike="Bike trail",
    backcountry="Backcountry sites", walkin="Walk-in sites", group="Group camping",
    barrier="Barrier-free sites", pets="Pet beach", petfree="Pet-free areas",
    radio="Radio-free areas", visitor="Visitor centre", ev="EV charging", winter="Winter camping",
    roofed="Cabins / yurts", playground="Playground", dunes="Sand dunes", amphi="Amphitheatre",
)

# sort = display order (popular -> not). Lower shows first.
PARKS = {
  "killbear": dict(sort=20, name="Killbear", region="Near North Park · Nobel",
    url="https://www.ontarioparks.ca/park/killbear",
    blurb="Seven campgrounds on a Georgian Bay peninsula, windswept pines, big sand beaches. No backcountry.",
    fishing="Smallmouth bass, lake trout, walleye, pike, perch", fmz="FMZ 14 (Georgian Bay)",
    facilities=[F["elec"],F["showers"],F["flush"],F["vault"],F["laundry"],F["water"],F["dump"],F["firewood"],
      F["store"],F["beaches"],F["boat"],F["trails"],F["group"],F["barrier"],F["pets"],F["playground"],
      F["radio"],F["ev"],F["visitor"],F["winter"],F["roofed"]]),
  "grundy": dict(sort=30, name="Grundy Lake", region="Near North Park · Britt",
    url="https://www.ontarioparks.ca/park/grundylake",
    blurb="Nine campgrounds across four inland lakes. Smooth-rock swimming, quiet water, no motorboats.",
    fishing="Northern pike, bass, panfish", fmz="FMZ 15",
    facilities=[F["elec"],F["showers"],F["flush"],F["laundry"],F["water"],F["dump"],F["firewood"],F["store"],
      F["beaches"],F["canoe"],F["pfd"],F["trails"],F["backcountry"],F["group"],F["roofed"],F["barrier"],
      F["pets"],F["radio"],F["visitor"]]),
  # ---- new batch: popular, close to the GTA ----
  "sibbaldpoint": dict(sort=40, name="Sibbald Point", region="Central Park · Sutton",
    url="https://www.ontarioparks.ca/park/sibbaldpoint",
    blurb="One of Ontario's busiest parks, a big sandy Lake Simcoe beach, with 600+ shaded sites split between the non-electric East and all-electric West campgrounds.",
    fishing="Lake Simcoe, perch, bass, pike, lake trout", fmz="FMZ 16 (Lake Simcoe)",
    facilities=[F["elec"],F["showers"],F["flush"],F["vault"],F["laundry"],F["water"],F["dump"],F["firewood"],
      F["store"],F["beaches"],F["boat"],F["trails"],F["group"],F["barrier"],F["playground"],F["radio"],F["pets"]]),
  "darlington": dict(sort=50, name="Darlington", region="Central Park · Bowmanville",
    url="https://www.ontarioparks.ca/park/darlington",
    blurb="A lakefront park on Lake Ontario. Three campgrounds, Lakeside (all electric), Cliffside, and Hilltop, with beaches, birding, and marsh trails. A rail line runs past the park.",
    fishing="Lake Ontario & McLaughlin Bay, salmon, trout, bass, pike", fmz="FMZ 20 (Lake Ontario)",
    facilities=[F["elec"],F["showers"],F["flush"],F["vault"],F["laundry"],F["water"],F["dump"],F["firewood"],
      F["store"],F["beaches"],F["boat"],F["trails"],F["group"],F["barrier"],F["playground"],F["radio"],
      F["visitor"],F["amphi"],F["pets"]]),
  "brontecreek": dict(sort=60, name="Bronte Creek", region="Southwest Park · Oakville",
    url="https://www.ontarioparks.ca/park/brontecreek",
    blurb="The most urban park in the system, in Oakville. 144 all-electric sites in four small loops, plus a Play Barn, historic farm, and trails. Day-use and campground have separate entrances; no beach.",
    fishing="Bronte Creek, smallmouth bass, panfish", fmz="FMZ 16",
    facilities=[F["elec"],F["showers"],F["flush"],F["laundry"],F["water"],F["dump"],F["firewood"],F["store"],
      F["trails"],F["bike"],F["group"],F["barrier"],F["playground"],F["radio"],F["roofed"],F["amphi"],F["visitor"]]),
  "sandbanks": dict(sort=70, name="Sandbanks", region="Southeast Park · Prince Edward County",
    url="https://www.ontarioparks.ca/park/sandbanks",
    blurb="The world's largest baymouth sandbar, with dune beaches on Lake Ontario and calm swimming on West Lake. Books out fast.",
    fishing="West and East Lake: bass, pike, panfish", fmz="FMZ 20 (Lake Ontario waters)",
    facilities=[F["elec"],F["showers"],F["flush"],F["vault"],F["laundry"],F["water"],F["dump"],F["store"],
      F["beaches"],F["rentals"],F["trails"],F["group"],F["barrier"],F["pets"],F["visitor"],F["roofed"],F["dunes"]]),
  "pinery": dict(sort=80, name="Pinery", region="Southwest Park · Grand Bend",
    url="https://www.ontarioparks.ca/park/pinery",
    blurb="A rare oak savanna on Lake Huron with 10 km of sand beach and the paddleable Old Ausable Channel. Very busy in summer.",
    fishing="Old Ausable Channel: largemouth bass, pike, panfish", fmz="FMZ 16 (channel) / FMZ 13 (Lake Huron)",
    facilities=[F["elec"],F["showers"],F["flush"],F["vault"],F["laundry"],F["water"],F["dump"],F["store"],
      F["beaches"],F["rentals"],F["trails"],F["bike"],F["group"],F["barrier"],F["petfree"],F["radio"],F["visitor"],
      F["winter"],F["roofed"],F["amphi"],F["dunes"]]),
  "arrowhead": dict(sort=90, name="Arrowhead", region="Central Park · Huntsville",
    url="https://www.ontarioparks.ca/park/arrowhead",
    blurb="Three campgrounds near Huntsville, with Stubb's Falls, a swimmable lake, and a famous winter ice-skating trail.",
    fishing="Arrowhead and Mayflower Lakes: bass, pike, rainbow trout", fmz="FMZ 15",
    facilities=[F["elec"],F["showers"],F["flush"],F["vault"],F["laundry"],F["water"],F["dump"],F["store"],
      F["beaches"],F["rentals"],F["trails"],F["bike"],F["group"],F["barrier"],F["pets"],F["radio"],F["visitor"],
      F["winter"],F["roofed"]]),
  "bonecho": dict(sort=100, name="Bon Echo", region="Southeast Park · Cloyne",
    url="https://www.ontarioparks.ca/park/bonecho",
    blurb="Home to the 100 m Mazinaw Rock and its Indigenous pictographs, reached by the Mugwump ferry. Two lakeside campgrounds plus walk-in and backcountry sites.",
    fishing="Mazinaw Lake: lake trout, bass, walleye", fmz="FMZ 18",
    facilities=[F["elec"],F["showers"],F["flush"],F["vault"],F["laundry"],F["water"],F["dump"],F["firewood"],F["store"],
      F["beaches"],F["boat"],F["rentals"],F["trails"],F["backcountry"],F["walkin"],F["group"],F["barrier"],F["radio"],F["visitor"],F["roofed"]]),
  "awenda": dict(sort=110, name="Awenda", region="Central Park · Penetanguishene",
    url="https://www.ontarioparks.ca/park/awenda",
    blurb="A forested peninsula on Georgian Bay with five beaches and six campgrounds shaded by sugar maples. Kettle's Lake is motor-free for paddling, and 30 km of trails wind to the shore.",
    fishing="Georgian Bay: bass, pike, walleye, panfish; Kettle's Lake: bass, panfish", fmz="FMZ 14 (Georgian Bay)",
    facilities=[F["elec"],F["showers"],F["flush"],F["vault"],F["laundry"],F["water"],F["dump"],F["firewood"],F["store"],
      F["beaches"],F["rentals"],F["trails"],F["bike"],F["group"],F["barrier"],F["radio"],F["petfree"],F["pets"],F["visitor"],F["amphi"],F["roofed"],F["playground"]]),
  "killarney": dict(sort=120, name="Killarney", region="Near North Park · Killarney",
    url="https://www.ontarioparks.ca/park/killarney",
    blurb="A wilderness park of pink granite and white La Cloche quartzite ridges that inspired the Group of Seven. One car campground on George Lake, plus a legendary canoe interior and the 78 km La Cloche Silhouette Trail.",
    fishing="George Lake and Georgian Bay: smallmouth bass, pike", fmz="FMZ 10",
    facilities=[F["showers"],F["flush"],F["vault"],F["laundry"],F["water"],F["dump"],F["firewood"],F["store"],
      F["beaches"],F["boat"],F["rentals"],F["trails"],F["backcountry"],F["group"],F["barrier"],F["visitor"],F["winter"],F["roofed"]]),
  "presquile": dict(sort=130, name="Presqu'ile", region="Southeast Park · Brighton",
    url="https://www.ontarioparks.ca/park/presquile",
    blurb="A Lake Ontario peninsula famous for spring and fall bird migration and monarch butterflies. Eight campgrounds, a long sandy beach, a marsh boardwalk, and a historic lighthouse.",
    fishing="Presqu'ile Bay and Lake Ontario: bass, pike, walleye, panfish", fmz="FMZ 20 (Lake Ontario)",
    facilities=[F["elec"],F["showers"],F["flush"],F["vault"],F["laundry"],F["water"],F["dump"],F["firewood"],F["store"],
      F["beaches"],F["boat"],F["trails"],F["walkin"],F["group"],F["barrier"],F["radio"],F["visitor"],F["roofed"],F["playground"]]),
  "silentlake": dict(sort=140, name="Silent Lake", region="Southeast Park · Bancroft",
    url="https://www.ontarioparks.ca/park/silentlake",
    blurb="A quiet, motor-free lake near Bancroft with two forested campgrounds and plenty of walk-in sites. Good for paddling and fishing, with hiking and mountain-bike trails.",
    fishing="Silent Lake: smallmouth and largemouth bass, lake trout", fmz="FMZ 15",
    facilities=[F["elec"],F["showers"],F["flush"],F["vault"],F["laundry"],F["water"],F["dump"],F["firewood"],F["store"],
      F["beaches"],F["rentals"],F["trails"],F["bike"],F["walkin"],F["group"],F["barrier"],F["pets"],F["winter"],F["roofed"]]),
  "macgregorpoint": dict(sort=150, name="MacGregor Point", region="Southwest Park · Port Elgin",
    url="https://www.ontarioparks.ca/park/macgregorpoint",
    blurb="A Lake Huron park near Port Elgin known for the Huron Fringe Birding Festival, with three campgrounds, coastal wetlands, and sunset beaches. Trails and boardwalks wind through fen and forest.",
    fishing="Lake Huron: bass, pike, salmon, trout", fmz="FMZ 13 (Lake Huron)",
    facilities=[F["elec"],F["showers"],F["flush"],F["vault"],F["laundry"],F["water"],F["dump"],F["firewood"],F["store"],
      F["beaches"],F["trails"],F["bike"],F["walkin"],F["group"],F["barrier"],F["pets"],F["radio"],F["visitor"],F["winter"],F["roofed"],F["playground"]]),
  "restoule": dict(sort=160, name="Restoule", region="Near North Park · Restoule",
    url="https://www.ontarioparks.ca/park/restoule",
    blurb="A quiet, off-the-beaten-path park near North Bay with three lakeside campgrounds, big fishing lakes, and the must-do Fire Tower Trail up Stormy Lake Bluff.",
    fishing="Restoule and Stormy Lakes: walleye, lake trout, pike, muskie, smallmouth bass", fmz="FMZ 11",
    facilities=[F["elec"],F["showers"],F["flush"],F["vault"],F["laundry"],F["water"],F["dump"],F["firewood"],F["store"],
      F["beaches"],F["boat"],F["rentals"],F["trails"],F["bike"],F["backcountry"],F["walkin"],F["barrier"],F["pets"]]),
  "sixmilelake": dict(sort=170, name="Six Mile Lake", region="Central Park · Port Severn",
    url="https://www.ontarioparks.ca/park/sixmilelake",
    blurb="A small, family-favourite Muskoka park just off Highway 400 with seven campgrounds, three beaches, and calm, sheltered water for paddling. One trail honours painter David Milne.",
    fishing="Six Mile Lake: bass, pike, panfish", fmz="FMZ 15",
    facilities=[F["elec"],F["showers"],F["flush"],F["vault"],F["laundry"],F["water"],F["dump"],F["firewood"],F["store"],
      F["beaches"],F["boat"],F["rentals"],F["trails"],F["walkin"],F["barrier"],F["playground"],F["pets"]]),
  "balsamlake": dict(sort=180, name="Balsam Lake", region="Central Park · Coboconk",
    url="https://www.ontarioparks.ca/park/balsamlake",
    blurb="A big family park on Balsam Lake, the high point of the Trent-Severn Waterway, with a long sandy beach and eight campgrounds. Good fishing for bass, walleye, and muskie.",
    fishing="Balsam Lake: largemouth and smallmouth bass, walleye, muskie", fmz="FMZ 17",
    facilities=[F["elec"],F["showers"],F["flush"],F["vault"],F["laundry"],F["water"],F["dump"],F["firewood"],F["store"],
      F["beaches"],F["boat"],F["rentals"],F["trails"],F["walkin"],F["group"],F["barrier"],F["playground"],F["pets"],F["radio"],F["roofed"]]),
  "longpoint": dict(sort=190, name="Long Point", region="Southwest Park · Port Rowan",
    url="https://www.ontarioparks.ca/park/longpoint",
    blurb="A Lake Erie sandspit and UNESCO biosphere near Port Rowan, famous for birding and 2 km of soft sand beach. Four campgrounds, some right in the dunes. Beach-focused, with little hiking.",
    fishing="Long Point Bay and Lake Erie: bass, walleye, perch, pike", fmz="FMZ 19 (Lake Erie)",
    facilities=[F["elec"],F["showers"],F["flush"],F["vault"],F["laundry"],F["water"],F["dump"],F["firewood"],F["store"],
      F["beaches"],F["boat"],F["barrier"],F["playground"],F["pets"]]),
  "charlestonlake": dict(sort=200, name="Charleston Lake", region="Southeast Park · Lyndhurst",
    url="https://www.ontarioparks.ca/park/charlestonlake",
    blurb="A clear Canadian Shield lake in eastern Ontario near Brockville, with three wooded campgrounds, boat-in interior sites, and a strong trail network. Sandstone Island and the 10 km Tallow Rock Bay loop are highlights.",
    fishing="Charleston Lake: smallmouth and largemouth bass, lake trout, pike", fmz="FMZ 18",
    facilities=[F["elec"],F["showers"],F["flush"],F["vault"],F["laundry"],F["water"],F["dump"],F["firewood"],F["store"],
      F["beaches"],F["boat"],F["rentals"],F["trails"],F["backcountry"],F["walkin"],F["group"],F["barrier"],F["playground"],F["pets"],F["visitor"],F["amphi"],F["roofed"]]),
  "algonquintea": dict(sort=10, name="Tea Lake", region="Algonquin · Highway 60",
    url="https://www.ontarioparks.ca/park/algonquin",
    blurb="KM 11 on the Highway 60 corridor. A small, simple campground where you can paddle straight out onto Canoe Lake.",
    fishing="Brook trout, lake trout, smallmouth bass (special fishery)", fmz="FMZ 15 · special park regulations",
    facilities=[F["vault"],F["water"],F["firewood"],F["beaches"],F["pets"]]),
  "algonquincanisbay": dict(sort=11, name="Canisbay", region="Algonquin · Highway 60",
    url="https://www.ontarioparks.ca/park/algonquin",
    blurb="KM 23. A big hardwood campground on Canisbay Lake, dog-free and radio-free, with no motorboats allowed.",
    fishing="Brook trout, lake trout, smallmouth bass (special fishery)", fmz="FMZ 15 · special park regulations",
    facilities=[F["showers"],F["flush"],F["water"],F["firewood"],F["beaches"],F["radio"],F["petfree"],F["trails"]]),
  "algonquinmew": dict(sort=12, name="Mew Lake", region="Algonquin · Highway 60",
    url="https://www.ontarioparks.ca/park/algonquin",
    blurb="KM 30.6. Open year-round with yurts, electrical sites, and the Old Railway Bike Trail.",
    fishing="Brook trout, lake trout, smallmouth bass (special fishery)", fmz="FMZ 15 · special park regulations",
    facilities=[F["elec"],F["showers"],F["flush"],F["laundry"],F["water"],F["dump"],F["firewood"],F["beaches"],F["bike"],F["winter"],F["roofed"]]),
  "algonquintworivers": dict(sort=13, name="Lake of Two Rivers", region="Algonquin · Highway 60",
    url="https://www.ontarioparks.ca/park/algonquin",
    blurb="KM 31. The most scenic corridor campground, next to the Visitor Centre on Lake of Two Rivers.",
    fishing="Brook trout, lake trout, smallmouth bass (special fishery)", fmz="FMZ 15 · special park regulations",
    facilities=[F["elec"],F["showers"],F["flush"],F["water"],F["firewood"],F["beaches"],F["bike"],F["trails"]]),
  "algonquinpog": dict(sort=14, name="Pog Lake", region="Algonquin · Highway 60",
    url="https://www.ontarioparks.ca/park/algonquin",
    blurb="KM 37. The largest corridor campground, with electrical sites and the quiet Section C.",
    fishing="Brook trout, lake trout, smallmouth bass (special fishery)", fmz="FMZ 15 · special park regulations",
    facilities=[F["elec"],F["showers"],F["flush"],F["laundry"],F["water"],F["dump"],F["firewood"],F["beaches"],F["radio"],F["trails"]]),
  "algonquinkearney": dict(sort=15, name="Kearney Lake", region="Algonquin · Highway 60",
    url="https://www.ontarioparks.ca/park/algonquin",
    blurb="KM 36.5. Mid-size and non-electric, with two beaches on Kearney Lake.",
    fishing="Brook trout, lake trout, smallmouth bass (special fishery)", fmz="FMZ 15 · special park regulations",
    facilities=[F["showers"],F["flush"],F["water"],F["firewood"],F["beaches"]]),
  "algonquinraccoon": dict(sort=16, name="Raccoon Lake", region="Algonquin · Highway 60",
    url="https://www.ontarioparks.ca/park/algonquin",
    blurb="KM 41. The smallest and quietest campground on the corridor.",
    fishing="Brook trout, lake trout, smallmouth bass (special fishery)", fmz="FMZ 15 · special park regulations",
    facilities=[F["vault"],F["water"],F["firewood"],F["trails"]]),
  "algonquinrock": dict(sort=17, name="Rock Lake", region="Algonquin · Highway 60",
    url="https://www.ontarioparks.ca/park/algonquin",
    blurb="KM 40, down Rock Lake Road. Pictographs, canoe access, and a busy beach.",
    fishing="Brook trout, lake trout, smallmouth bass (special fishery)", fmz="FMZ 15 · special park regulations",
    facilities=[F["showers"],F["flush"],F["water"],F["dump"],F["firewood"],F["beaches"],F["boat"],F["trails"]]),
  "algonquinachray": dict(sort=18, name="Achray", region="Algonquin · Barron Canyon Road",
    url="https://www.ontarioparks.ca/park/algonquin",
    blurb="On Grand Lake on the remote east side of the park, near the Barron Canyon. Rustic sites and cabins.",
    fishing="Brook trout, lake trout, smallmouth bass (special fishery)", fmz="FMZ 15 · special park regulations",
    facilities=[F["vault"],F["water"],F["firewood"],F["beaches"],F["boat"],F["backcountry"],F["roofed"]]),
  "lakesuperior": dict(sort=400, name="Lake Superior", region="Northern Park · Wawa",
    url="https://www.ontarioparks.ca/park/lakesuperior",
    blurb="A vast wilderness park on Superior's east shore. The Agawa Rock pictographs, Old Woman Bay, and some of the best day hiking in Ontario.",
    fishing="Lake trout, brook trout, salmon; brook trout in the inland lakes", fmz="FMZ 10 (inland lakes) / FMZ 9 (Lake Superior)",
    facilities=[F["elec"],F["showers"],F["flush"],F["vault"],F["laundry"],F["water"],F["dump"],F["firewood"],
      F["store"],F["beaches"],F["rentals"],F["trails"],F["backcountry"],F["group"],F["barrier"],F["radio"],F["visitor"],F["roofed"]]),
  "turkeypoint": dict(sort=401, name="Turkey Point", region="Southwest Park · Turkey Point",
    url="https://www.ontarioparks.ca/park/turkeypoint",
    blurb="A bluff-top park over Long Point Bay with a 2 km shallow beach and the only golf course in an Ontario park.",
    fishing="Long Point Bay: perch, bass, walleye, pike", fmz="FMZ 19 (Long Point Bay)",
    facilities=[F["elec"],F["showers"],F["flush"],F["vault"],F["laundry"],F["water"],F["dump"],F["firewood"],
      F["beaches"],F["trails"],F["bike"],F["group"],F["barrier"],F["playground"],F["radio"]]),
  "emily": dict(sort=402, name="Emily", region="Central Park · Omemee",
    url="https://www.ontarioparks.ca/park/emily",
    blurb="A Kawarthas family park on the Pigeon River. Warm-water swimming, easy paddling, and big grassy sites.",
    fishing="Pigeon River: walleye, muskie, bass, panfish", fmz="FMZ 17",
    facilities=[F["elec"],F["showers"],F["flush"],F["vault"],F["laundry"],F["water"],F["dump"],F["firewood"],
      F["store"],F["beaches"],F["boat"],F["rentals"],F["trails"],F["group"],F["barrier"],F["playground"],F["radio"],F["amphi"]]),
  "mara": dict(sort=403, name="Mara", region="Central Park · Orillia",
    url="https://www.ontarioparks.ca/park/mara",
    blurb="A small beach park on Lake Simcoe minutes from Orillia. One of the lake's best sandy beaches, with warm, shallow swimming.",
    fishing="Lake Simcoe: perch, bass, walleye, lake trout", fmz="FMZ 16 (Lake Simcoe)",
    facilities=[F["elec"],F["showers"],F["flush"],F["vault"],F["water"],F["dump"],F["firewood"],
      F["beaches"],F["trails"],F["barrier"],F["playground"]]),
  "bonnechere": dict(sort=404, name="Bonnechere", region="Southeast Park · Killaloe",
    url="https://www.ontarioparks.ca/park/bonnechere",
    blurb="An Ottawa Valley classic where the Little Bonnechere River meets Round Lake. Sandy beach, river paddling, and the Footprints in Time walks.",
    fishing="Round Lake: lake trout, bass, walleye", fmz="FMZ 15",
    facilities=[F["elec"],F["showers"],F["flush"],F["vault"],F["laundry"],F["water"],F["dump"],F["firewood"],
      F["store"],F["beaches"],F["boat"],F["rentals"],F["trails"],F["group"],F["barrier"],F["radio"],F["visitor"],F["roofed"],F["playground"]]),
  "mikisew": dict(sort=405, name="Mikisew", region="Near North Park · South River",
    url="https://www.ontarioparks.ca/park/mikisew",
    blurb="A quiet Almaguin park on Eagle Lake with three sandy beaches, island paddling, disc golf, and a great dog beach.",
    fishing="Eagle Lake: bass, walleye, pike, panfish", fmz="FMZ 11",
    facilities=[F["elec"],F["showers"],F["flush"],F["vault"],F["laundry"],F["water"],F["dump"],F["firewood"],
      F["beaches"],F["boat"],F["trails"],F["bike"],F["group"],F["barrier"],F["pets"],F["playground"]]),
  "rondeau": dict(sort=406, name="Rondeau", region="Southwest Park · Morpeth",
    url="https://www.ontarioparks.ca/park/rondeau",
    blurb="A Carolinian sandspit between Lake Erie and Rondeau Bay. Old-growth tulip trees, 11 km of beach, and warbler-famous birding.",
    fishing="Rondeau Bay: largemouth bass, perch, crappie, pike", fmz="FMZ 19 (Lake Erie)",
    facilities=[F["elec"],F["showers"],F["flush"],F["vault"],F["laundry"],F["water"],F["dump"],F["firewood"],
      F["store"],F["beaches"],F["boat"],F["trails"],F["bike"],F["group"],F["barrier"],F["pets"],F["visitor"],F["playground"]]),
  "neys": dict(sort=407, name="Neys", region="Northern Park · Marathon",
    url="https://www.ontarioparks.ca/park/neys",
    blurb="A driftwood-strewn Superior beach park near Marathon, once the wartime Neys 100 prisoner-of-war camp. Pic Island views the Group of Seven painted.",
    fishing="Lake Superior and the Little Pic River: lake trout, salmon, pike", fmz="FMZ 9 (Lake Superior)",
    facilities=[F["elec"],F["showers"],F["flush"],F["vault"],F["laundry"],F["water"],F["dump"],F["firewood"],
      F["store"],F["beaches"],F["boat"],F["rentals"],F["trails"],F["group"],F["barrier"],F["visitor"],F["roofed"]]),
  "chutes": dict(sort=408, name="Chutes", region="Northern Park · Massey",
    url="https://www.ontarioparks.ca/park/chutes",
    blurb="Waterfalls and the Seven Sisters rapids on the Aux Sables River, the only park campground on Highway 17 between Sudbury and the Sault.",
    fishing="Aux Sables River: pike, walleye, smallmouth bass", fmz="FMZ 10",
    facilities=[F["elec"],F["showers"],F["flush"],F["vault"],F["laundry"],F["water"],F["dump"],F["firewood"],
      F["beaches"],F["trails"],F["group"],F["barrier"],F["pets"],F["radio"],F["playground"]]),
  "fairbank": dict(sort=409, name="Fairbank", region="Northern Park · Sudbury",
    url="https://www.ontarioparks.ca/park/fairbank",
    blurb="A crystal-clear, spring-fed lake on the rim of the Sudbury Basin meteorite crater. Waterfront sites you can launch a canoe from.",
    fishing="Fairbank Lake: smallmouth bass, lake trout", fmz="FMZ 10",
    facilities=[F["elec"],F["showers"],F["flush"],F["vault"],F["laundry"],F["water"],F["dump"],F["firewood"],
      F["beaches"],F["boat"],F["rentals"],F["trails"],F["group"],F["barrier"],F["pets"],F["playground"]]),
}

# (park, name, sub, sort, range_or_labels)
CAMPGROUNDS = [
  # Grundy
  ("grundy","White Spruce","Gut Lake · non-electric · quietest",1,("range",1,32)),
  ("grundy","Poplar","Gurd Lake · largest · pet-friendly",2,("range",300,370)),
  ("grundy","Trailer","Gurd Lake · all electric",3,("range",200,236)),
  ("grundy","Hemlock","Gurd Lake · radio-free",4,("range",100,165)),
  ("grundy","Red Maple","Grundy Lake · radio & pet-free",5,("range",400,446)),
  ("grundy","White Pine","Grundy Lake · Main Beach",6,("range",500,566)),
  ("grundy","White Birch","Grundy Lake · west shore",7,("range",600,657)),
  ("grundy","Jack Pine","Grundy Lake · canoe launch",8,("range",700,756)),
  ("grundy","Balsam","Clear Lake · sunsets",9,("range",818,863)),
  ("grundy","Backcountry","Canoe-in · B10 hike-in",10,("labels",[f"B{i}" for i in range(1,11)])),
  # Killbear
  ("killbear","Kilcoursie Bay","All electric · long family beach",1,("range",1,118)),
  ("killbear","Beaver Dams","Electric · winter camping",2,("range",204,378)),
  ("killbear","Granite Saddle","Radio-free, no comfort station",3,("range",1000,1055)),
  ("killbear","Georgian","Radio-free",4,("range",400,476)),
  ("killbear","Harold Point","Radio-free · some electric",5,("range",500,631)),
  ("killbear","Lighthouse Point","Radio-free, the largest campground, boat launch",6,("range",1101,1497)),
  ("killbear","Blind Bay","Non-electric, quiet, boat launch",7,("range",700,881)),
  # Algonquin (each campground numbers from 1)
  ("algonquintea","Tea Lake","KM 11 · Paddle to Canoe Lake",1,("range",1,46)),
  ("algonquincanisbay","Canisbay Lake","KM 23 · Hardwood · Dog and radio-free · No motorboats",1,("range",1,242)),
  ("algonquinmew","Mew Lake","KM 30.6 · Year-round · Yurts · Bike trail",1,("range",1,130)),
  ("algonquintworivers","Lake of Two Rivers","KM 31 · By the Visitor Centre · Most scenic",1,("range",1,241)),
  ("algonquinpog","Pog Lake","KM 37 · Largest · Electrical · Quiet Section C",1,("range",1,286)),
  ("algonquinkearney","Kearney Lake","KM 36.5 · No electrical · Two beaches",1,("range",1,104)),
  ("algonquinraccoon","Raccoon Lake","KM 41 · Small and quiet",1,("range",1,48)),
  ("algonquinrock","Rock Lake","KM 40 · Pictographs · Canoe access",1,("range",1,120)),
  ("algonquinachray","Achray","East side · Remote · Grand Lake · Cabins",1,("range",1,45)),
  # Sibbald Point
  ("sibbaldpoint","East Campground","Lake Simcoe · non-electric · 5 loops",1,("range",200,514)),
  ("sibbaldpoint","West Campground","All electric · 5 loops · 500 loop trailers",2,("range",515,801)),
  # Darlington
  ("darlington","Lakeside","All electric · radio-free · by the beach",1,("range",1,100)),
  ("darlington","Cliffside","Lake views (114-116, 158-161) · some electric",2,("range",101,184)),
  ("darlington","Hilltop","Mostly non-electric · largest",3,("range",200,335)),
  # Bronte Creek (all electric)
  ("brontecreek","Prairie","Larger RVs · all electric",1,("range",101,136)),
  ("brontecreek","Savannah","Radio-free · yurts",2,("range",201,236)),
  ("brontecreek","Woodlands","Wooded · small trailers & tents",3,("range",301,336)),
  ("brontecreek","Ravine","Private wooded sites",4,("range",401,436)),
  ("sandbanks","Outlet River","Outlet Beach waterfront, popular, some electric",1,("range",1,250)),
  ("sandbanks","Cedars","Non-electric, private and shaded, near the office",2,("range",300,399)),
  ("sandbanks","Richardson's","West Lake, vault toilets only, mostly sunny",3,("range",400,449)),
  ("sandbanks","Woodlands","All electric, open and sunny",4,("range",600,739)),
  ("sandbanks","West Lake","All electric, newest comfort station",5,("range",800,874)),
  ("pinery","Dunes","Areas 1-4, by the beach and Visitor Centre, Area 4 pet-free",1,("range",1,329)),
  ("pinery","Burley","Non-electric, older pines, near the beach",2,("range",330,599)),
  ("pinery","Riverside","Old Ausable Channel, pull-throughs, Area 3 radio-free, year-round",3,("range",600,1000)),
  ("arrowhead","Lumby","North and South, mixed, vault toilets, radio-free South",1,("range",1,134)),
  ("arrowhead","East River","Electric, cabins, closest to Stubb's Falls",2,("range",200,351)),
  ("arrowhead","Roe","Electric, large private sites, near the beach",3,("range",400,501)),
  ("arrowhead","Pull-Through","All electric, year-round",4,("labels",["PT1","PT2","PT3","PT4","PT5","PT6","PT7"])),
  ("bonecho","Sawmill Bay","Mazinaw Lake, electric, 5 walk-in, yurts",1,("range",1,163)),
  ("bonecho","Midway","Mazinaw Lake, radio-free",2,("range",164,275)),
  ("bonecho","Fairway","Mazinaw Lake, electric",3,("range",276,395)),
  ("bonecho","Hardwood Hill","Maple-beech forest, non-electric, radio-free",4,("range",400,440)),
  ("bonecho","Backcountry","Abes and Essens, hike-in",5,("labels",["A1","A2","A3","A4","A5"])),
  ("awenda","Turtle","Near the entrance, laundry",1,("range",1,70)),
  ("awenda","Hawk","Some electric, laundry",2,("range",71,120)),
  ("awenda","Bear","Radio-free, laundry",3,("range",121,170)),
  ("awenda","Deer","Radio-free",4,("range",171,205)),
  ("awenda","Wolf","All electric, near the beach",5,("range",206,250)),
  ("awenda","Snake","Radio-free and dog-free, near the beaches",6,("range",251,333)),
  ("killarney","George Lake","Named loops (Bear Alley, Trailer Court, ...), yurts and cabins",1,("labels",["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","35","36","37","38","39","40","41","42","43","44","45","46","47","48","49","50","51","52","53","54","55","56","57","58","59","60","61","62","63","64","65","66","67","68","69","70","71","72","73","74","75","76","77","78","79","80","81","82","83","84","87","88","89","90","91","92","93","94","95","96","97","98","99","100","101","102","103","104","105","106","107","108","111","112","113","115","116","117","118","120","121","122","123","124","125","126","127","128","129","130","131","132","133","134","135","136","137","138","139","140","141","142","143"])),  ("presquile","High Bluff","Mostly electric, open and sunny, best waterfront",1,("range",1,100)),
  ("presquile","Pines","Small, all electric, Scots pine",2,("range",101,122)),
  ("presquile","Lakeside","Non-electric, a few on the lakeshore",3,("range",123,153)),
  ("presquile","Maples","Non-electric, mature forest",4,("range",154,213)),
  ("presquile","Trails End","Mostly electric, near the rocky shore",5,("range",214,260)),
  ("presquile","Craig's","Non-electric, radio-free, wooded",6,("range",261,305)),
  ("presquile","Hidden Valley","Non-electric, mature forest",7,("range",306,350)),
  ("presquile","Elmvale","Mostly non-electric, 6 walk-in on Lake Ontario",8,("range",351,394)),
  ("silentlake","Pincer Bay","Walk-in loops, near the beach, yurts",1,("range",1,99)),
  ("silentlake","Granite Ridge","Some electric, car sites, yurts, walk-in loop",2,("range",100,167)),
  ("macgregorpoint","Algonquin","Ashwoods, Cedar Lane, Birch Boulevard, all electric, yurts",1,("range",1,134)),
  ("macgregorpoint","Nipissing","Deer Drive, Egret Circle, Foxway, some electric",2,("range",200,304)),
  ("macgregorpoint","Huron","Radio and generator free, one walk-in",3,("range",500,604)),  ("restoule","Kettle Point","All electric, near the main beach and trails",1,("range",400,496)),
  ("restoule","Putts Point","Non-electric, private, best beach access",2,("range",200,307)),
  ("restoule","Bells Point","Non-electric, tents and small RVs, 10 walk-in, dog beach",3,("range",101,160)),
  ("sixmilelake","Lakeview Heights","Premium waterfront and electric, some walk-in",1,("range",1,50)),
  ("sixmilelake","Poplar","Non-electric, semi-private, low-traffic",2,("range",51,90)),
  ("sixmilelake","Oak","Non-electric, semi-private, quiet",3,("range",91,124)),
  ("sixmilelake","Maple","Non-electric, near the comfort station and beach",4,("range",125,170)),
  ("sixmilelake","Cedar","Waterfront walk-in, near the dog beach",5,("range",171,185)),
  ("sixmilelake","Pine","Electric, big rigs, near the highway",6,("range",186,199)),
  ("sixmilelake","Birch","Electric, near the beach, playground, and store",7,("range",200,225)),
  ("balsamlake","Ash","Electric, open, pull-throughs",1,("range",1,60)),
  ("balsamlake","Cedar","Electric and non-electric, radio-free",2,("range",61,160)),
  ("balsamlake","Elm","Non-electric, closest to the boat launch",3,("range",161,195)),
  ("balsamlake","Fir","Mostly electric, some private offshoots",4,("range",196,240)),
  ("balsamlake","Hawthorn","Non-electric, radio-free and generator-free",5,("range",241,310)),
  ("balsamlake","Maple","Electric, radio-free",6,("range",311,400)),
  ("balsamlake","Oak","Electric, a few lakeside sunrise sites",7,("range",401,499)),
  ("balsamlake","Eco","Walk-in, non-electric, radio-free",8,("labels",["E1","E2","E3","E4","E5","E6"])),
  ("longpoint","Cottonwood","Old Park, Carolinian forest, some electric, near the beach",1,("range",1,80)),
  ("longpoint","Monarch's Rest","Electric and non-electric, dune sites by the beach",2,("range",101,160)),
  ("longpoint","Firefly","Pull-through electric, bay side, short walk to the beach",3,("range",161,210)),
  ("longpoint","Turtle Dunes","Electric and non-electric, right behind the dunes",4,("range",211,270)),
  ("charlestonlake","Bayside","Lakeside, mature forest, mostly electric",1,("range",1,90)),
  ("charlestonlake","Meadowlands","Younger forest, sunnier sites, some electric",2,("range",100,180)),
  ("charlestonlake","Shady Ridge","By the beach, electric and non-electric, barrier-free sites",3,("range",300,372)),
  ("lakesuperior","Agawa Bay","On the Lake Superior beach · 38 electrical · 300s radio-free",1,("range",1,147)),
  ("lakesuperior","Rabbit Blanket Lake","Inland lake · 20 electrical · Quieter and shadier",2,("range",1,60)),
  ("turkeypoint","Walking Stick Woods","Pull-throughs · Site 81 barrier-free",1,("range",1,120)),
  ("turkeypoint","Whippoorwill","Central · Site 212 barrier-free",2,("range",150,244)),
  ("turkeypoint","Fin and Feather","Radio-free · 8 electrical",3,("range",250,269)),
  ("emily","Cedars","Tent only · Non-electric · Sites 1-36 radio-free",1,("range",1,57)),
  ("emily","Hill","Mixed electric · Near the beach and amphitheatre",2,("range",100,190)),
  ("emily","Circle","Electric loop · Big rigs",3,("range",200,290)),
  ("emily","Hilltop","Sunny and grassy · Some electric",4,("range",300,370)),
  ("mara","Mara Campground","Electric and non-electric · Steps from the beach",1,("range",1,105)),
  ("bonnechere","Tall Pines","Old white pines · 43 electrical · Sites 37 and 39 barrier-free",1,("range",1,59)),
  ("bonnechere","River Loop","Riverside sites · Non-electric",2,("range",100,154)),
  ("bonnechere","Sandy Flats","Radio and generator-free",3,("range",200,214)),
  ("mikisew","Hardwoods","Rolling maple and oak hills · Mixed electric",1,("range",100,262)),
  ("mikisew","Pines","Red pine rows · Level sites · Mixed electric",2,("range",300,465)),
  ("rondeau","Rondeau Campground","Tree-named lanes · Mixed electric · 11 pull-throughs",1,("labels",[str(i) for i in list(range(1,258))+list(range(300,307))])),
  ("neys","Area 1","Lakefront · All electric pull-throughs",1,("range",1,35)),
  ("neys","Area 2","Lake side · Some electric",2,("range",36,70)),
  ("neys","Area 3","Shadier rows · Some electric",3,("range",71,97)),
  ("neys","Area 4","Wooded loop · Non-electric · Lookout trailhead",4,("range",100,146)),
  ("chutes","Chutes Campground","Seven Sisters, Red Pine, Log Drive, and Big Chute loops · 79 electrical · Radio-free near the falls",1,("range",1,130)),
  ("fairbank","Fairbank Campground","Many waterfront sites · 63 electrical",1,("range",1,112)),
]


TRAILS = [
  # (park, name, length_km, difficulty, detail, sort)
  ("algonquintea","Whiskey Rapids",2.1,"Moderate","Follows the Oxtongue River to Whiskey Rapids (km 7.2)",1),
  ("algonquintea","Hardwood Lookout",1.0,"Moderate","Hardwood forest to a view over Smoke Lake (km 13.8)",2),
  ("algonquintea","Mizzy Lake",10.8,"Difficult","Best trail for wildlife; nine ponds; no dogs allowed (km 15.4)",3),
  ("algonquincanisbay","Peck Lake",2.3,"Moderate","Circles the shoreline of Peck Lake (km 19.2)",1),
  ("algonquincanisbay","Track and Tower",7.5,"Moderate to difficult","Lookout over Cache Lake and old railway history (km 25)",2),
  ("algonquintworivers","Two Rivers",2.3,"Easy to moderate","Short climb to a cliff-top lookout by the Visitor Centre (km 31)",1),
  ("algonquinpog","Centennial Ridges",10.4,"Difficult","Dramatic ridge-top lookouts; a full-day hike (km 37.6)",1),
  ("algonquinrock","Lookout Trail",2.1,"Difficult","Steep climb to a famous panoramic lookout (km 39.7)",1),
  ("algonquinrock","Booth's Rock",5.1,"Difficult","Two lakes and a cliff lookout, returning on an old railbed (Rock Lake Rd)",2),
  ("algonquinraccoon","Spruce Bog Boardwalk",1.5,"Easy","Accessible boardwalk across two black spruce bogs; great birding (km 42.5)",1),
  ("algonquinraccoon","Beaver Pond",2.0,"Moderate","Two beaver ponds and rocky lookouts (km 45.2)",2),

  ("killbear","Lighthouse Point",0.8,"Easy to moderate","Short loop to the tip of Killbear Point with Georgian Bay views",1),
  ("killbear","Twin Points",1.6,"Easy","Rock outcrops and forest out to rocky points and sandy beaches",2),
  ("killbear","Lookout Point",3.5,"Moderate","Forest and rock to a panoramic Georgian Bay lookout at the midpoint",3),
  ("killbear","Recreational Trail",6.0,"Easy to moderate","Runs the length of the park; popular for hiking and biking",4),

  ("grundy","Swan Lake",1.5,"Moderate to difficult","Nature reserve; rocky ridges, lookouts, and a wetland boardwalk",1),
  ("grundy","Gut Lake",2.5,"Moderate to difficult","Most popular; Canadian Shield rock, lakes and streams, a rope swing",2),
  ("grundy","Beaver Dams",3.6,"Moderate to difficult","Forest and wetlands; a Great Blue Heron rookery and a beaver dam",3),
  ("grundy","Pakeshkag Lake",5.2,"Easy","Multi-use linear trail past Beaver Lake wetland and backcountry sites",4),

  ("sibbaldpoint","Maidenhair Fern Trail",2.0,"Easy","Forest and varied ecosystems on the park's quiet south side",1),
  ("sibbaldpoint","Cultural History Trail",1.0,"Easy","Short walk past historical features including Eildon Hall",2),

  ("darlington","Burk Trail",1.25,"Moderate","Fields, forest, and a pioneer cemetery to a Lake Ontario lookout",1),
  ("darlington","McLaughlin Bay Trail",1.5,"Easy","Marsh ecosystem with nesting waterfowl and herons",2),
  ("darlington","Robinson Creek Trail",1.0,"Easy","Forested ravine loop from the Visitor Centre",3),
  ("darlington","Waterfront Trail",2.6,"Easy","A section of the 350 km Lake Ontario Waterfront Trail",4),

  ("brontecreek","Gateway Trail",1.5,"Easy","The campground trail, an easy loop close to your site",1),
  ("brontecreek","Maiden's Blush Trail",1.0,"Easy","Paved forest loop, wheelchair accessible (day-use area)",2),
  ("brontecreek","Trillium Trail",1.0,"Easy","Spring wildflowers and valley views (day-use area)",3),
  ("brontecreek","Half Moon Valley Trail",2.0,"Moderate","Ravine loop down to Bronte Creek with a boardwalk and some hills",4),
  ("brontecreek","Ravine Trail",2.7,"Moderate","Valley-top path to a scenic ravine lookout",5),
  ("sandbanks","Cedar Sands Nature Trail",2.0,"Easy","Interpretive loop along the Outlet River with two marsh lookouts",1),
  ("sandbanks","Sandbanks Dunes Trail",2.5,"Easy to moderate","Loops the world's largest baymouth dune system and its rare pannes",2),
  ("sandbanks","Woodlands Trail",3.5,"Easy","Old farm fields and hardwood forest linking the Main Gate to Dunes Beach",3),
  ("sandbanks","Lakeview Trail",2.4,"Easy","Connector through the centre of the park to Woodlands Campground",4),
  ("sandbanks","MacDonald Trail",1.5,"Easy","Quick link across fields and forest between the park's two sides",5),
  ("pinery","Cedar Trail",2.3,"Easy","Rare Oak Savanna with a viewing platform and a branch to the Lake Huron beach",1),
  ("pinery","Riverside Trail",1.0,"Easy","Old Ausable Channel floodplain; wheelchair accessible with viewing platforms",2),
  ("pinery","Heritage Trail",2.3,"Easy","Diverse habitats out to an Old Ausable Channel overlook",3),
  ("pinery","Wilderness Trail",2.8,"Easy to moderate","Loops to a sandy beach lookout on Lake Huron",4),
  ("pinery","Carolinian Trail",1.8,"Moderate","Hilly floodplain forest of rare Carolinian species",5),
  ("pinery","Nipissing Trail",2.0,"Difficult","Climbs Pinery's oldest, largest dune ridge for a park-wide view",6),
  ("arrowhead","Stubb's Falls Trail",2.0,"Easy","Flat forest walk to the Little East River waterfall",1),
  ("arrowhead","Big Bend Lookout",0.5,"Easy","Short walk to a viewing deck over the Big East River gooseneck",2),
  ("arrowhead","Mayflower Lake Trail",2.1,"Moderate","Boardwalks and climbs around a deep spring-fed lake",3),
  ("arrowhead","Homesteaders Trail",2.8,"Moderate","Rugged terrain past abandoned 1870s farm fields",4),
  ("arrowhead","Beaver Meadow Trail",4.0,"Moderate","Porcupine Bluffs, a beaver pond, and the old Oke homestead",5),
  ("bonecho","Cliff Top Trail",1.5,"Difficult","Ferry or paddle to Mazinaw Rock, then stairs to three lookout decks over the pictographs",1),
  ("bonecho","High Pines Trail",1.7,"Moderate","Loop through pine and hemlock forest and wetlands with a Mazinaw Lake glimpse",2),
  ("bonecho","Shield Trail",4.8,"Moderate","Canadian Shield loop on the old Addington Road through hardwoods and a beaver swamp",3),
  ("bonecho","Bon Echo Creek Trail",1.0,"Easy","Short, leisurely walk along Bon Echo Creek (can be muddy)",4),
  ("bonecho","Abes and Essens Lake Trail",17.0,"Difficult","Backcountry loops (Clutes, Essens, Abes) with five hike-in campsites",5),
  ("awenda","Beaver Pond Trail",1.0,"Easy","Barrier-free boardwalk loop through a beaver-shaped nature reserve",1),
  ("awenda","Nipissing Trail",0.5,"Moderate","A 155-step staircase up the ancient Nipissing Bluff",2),
  ("awenda","Robitaille Homestead Trail",3.0,"Moderate","Past an abandoned 1902 farmstead to 11,500-year-old dunes",3),
  ("awenda","Beach Trail",4.0,"Easy","Along the Georgian Bay shoreline with Giant's Tomb Island views",4),
  ("awenda","Wendat Trail",5.0,"Easy","Loops Kettle's Lake with a marsh boardwalk and lots of birds",5),
  ("awenda","Bluff Trail",13.0,"Moderate","Long forested loop along the bluff linking the campgrounds and trails",6),
  ("killarney","Granite Ridge Trail",2.0,"Moderate","Climbs to two lookouts over the La Cloche Mountains and Georgian Bay",1),
  ("killarney","Cranberry Bog Trail",4.0,"Moderate","Bogs and marshes to A.Y. Jackson Lake, rich in birds and wildlife",2),
  ("killarney","Chikanishing Trail",3.0,"Moderate","Windswept Georgian Bay shoreline with logging-era iron rings",3),
  ("killarney","Lake of the Woods Trail",3.5,"Moderate to difficult","Old-growth forest and rocky outcrops with Silver Peak views",4),
  ("killarney","The Crack",6.0,"Difficult","A steep boulder scramble to a panoramic La Cloche ridge lookout",5),
  ("killarney","La Cloche Silhouette Trail",78.0,"Difficult","The legendary multi-day backcountry loop from George Lake",6),  ("presquile","Marsh Boardwalk",1.2,"Easy","Barrier-free boardwalk into the cattail marsh with two viewing towers",1),
  ("presquile","Jobes' Woods Trail",1.0,"Easy","Old maples, vernal pools, and boardwalks through an old-growth woodlot",2),
  ("presquile","Owen Point Trail",1.6,"Easy","Five lookouts over the natural beach and island bird colonies",3),
  ("presquile","Pioneer Trail",3.8,"Easy","Forest, plantations, and old fields in the heart of the peninsula",4),
  ("presquile","Newcastle Trail",4.3,"Easy","The park's longest loop through mature beech-maple forest",5),
  ("silentlake","Lakehead Loop Trail",1.5,"Easy","Short loop near the day-use beach",1),
  ("silentlake","Bonnie's Pond Trail",3.0,"Moderate","Forest loop past a quiet beaver pond",2),
  ("silentlake","Lakeshore Trail",15.0,"Difficult","A long loop encircling Silent Lake",3),
  ("macgregorpoint","Huron Fringe Trail",1.2,"Easy","Barrier-free boardwalk loop by the Visitor Centre through fen, swamp, and shore",1),
  ("macgregorpoint","Tower Trail",3.5,"Easy","Boardwalk and towers over marsh, good for herons, bitterns, and turtles",2),
  ("macgregorpoint","Old Shore Road Trail",7.0,"Easy","Follows the original shore road under maples and oaks along Lake Huron",3),
  ("macgregorpoint","Deer Run Trail",4.7,"Easy","Multi-use loop linking the three campgrounds and the Park Store",4),
  ("macgregorpoint","Lake Ridge Trail",2.5,"Easy","A wooded loop through the heart of the Carolinian forest",5),  ("restoule","Fire Tower Trail",4.1,"Difficult","Boardwalks and rocky ridges to a historic fire tower and the 100 m Stormy Lake Bluff view",1),
  ("restoule","River Trail",1.2,"Easy","A gentle walk along the west side of the Restoule River through mature forest",2),
  ("restoule","Angel's Point Trail",2.8,"Moderate","Hardwood-forest loops shared with mountain bikers",3),
  ("sixmilelake","Living Edge Trail",1.0,"Moderate","Rock barrens and wetland with beaver lodges and rare five-lined skinks",1),
  ("sixmilelake","David Milne Trail",0.5,"Moderate","Rolling Canadian Shield rocks that inspired the painter David Milne",2),
  ("sixmilelake","Marsh Trail",1.0,"Moderate","Circles a wetland alive with birds, dragonflies, and the odd moose",3),
  ("balsamlake","Lookout Trail",2.1,"Moderate","Through glacial eskers and kames to a panoramic lookout",1),
  ("balsamlake","Lorie's Link Trail",1.7,"Easy","Fields of wildflowers and a pine plantation",2),
  ("balsamlake","Woodland Trail",4.2,"Moderate","A forest trek with both natural and pioneer highlights",3),
  ("balsamlake","Pond Loop Trail",1.8,"Easy","Circles a pond full of aquatic life",4),
  ("charlestonlake","Quiddity Trail",2.4,"Easy","Boardwalk over a wetland to a scenic Charleston Lake lookout",1),
  ("charlestonlake","Sandstone Island Trail",3.3,"Moderate","Shoreline loop to a rock shelter used over 1,200 years ago",2),
  ("charlestonlake","Hemlock Ridge Trail",1.7,"Moderate","Hemlock ridge, a beaver pond, and sandstone rock crevices",3),
  ("charlestonlake","Shoreline Centennial Trail",2.0,"Easy","An easy interpretive walk along the lakeshore",4),
  ("charlestonlake","Tallow Rock Bay Trail",10.0,"Difficult","The park's longest loop across the Frontenac Arch to Slim Bay's floating bridge",5),
  ("charlestonlake","Blue Mountain Trail",5.7,"Difficult","A water-access climb to the highest peak in Leeds County",6),
  ("lakesuperior","Agawa Rock Pictographs",0.5,"Moderate","Rock ledge on Superior where generations of Ojibwe recorded dreams in red ochre",1),
  ("lakesuperior","Trapper's Trail",1.5,"Easy","Boardwalk loop around a beaver pond, good odds of moose",2),
  ("lakesuperior","South Old Woman River",2.5,"Moderate","Criss-crosses the river from Rabbit Blanket Lake Campground",3),
  ("lakesuperior","Nokomis",5.0,"Moderate","Lookouts over Old Woman Bay; ranked a top-five Canadian day hike",4),
  ("lakesuperior","Pinguisibi",6.0,"Moderate","Follows the Sand River past falls and rapids",5),
  ("lakesuperior","Orphan Lake",8.0,"Moderate","Loop to a Superior pebble beach and the Baldhead River falls",6),
  ("lakesuperior","Awausee",10.0,"Difficult","Big lookout loop over the Agawa Valley",7),
  ("lakesuperior","Peat Mountain",11.0,"Difficult","Climbs to a panorama above Rabbit Blanket Lake",8),
  ("lakesuperior","Coastal Trail",65.0,"Difficult","The legendary multi-day shoreline scramble from Agawa to Chalfant Cove",9),
  ("turkeypoint","Oak Savanna Trail",1.0,"Easy","Loop through rare oak savanna habitat",1),
  ("turkeypoint","Lookout Bluff Trail",2.2,"Easy","Bluff-top views over Long Point Bay, starts near the park office",2),
  ("turkeypoint","Fin and Feather Trail",4.0,"Moderate","Past the old hatchery pond to the Normandale Fish Hatchery",3),
  ("emily","Marsh Boardwalk Trail",1.0,"Easy","Boardwalk into the Pigeon River cattail marsh, great for birds and turtles",1),
  ("mara","Riverside Trail",1.0,"Easy","Short creekside nature loop with herons and osprey",1),
  ("bonnechere","McNaughton Trail",2.0,"Easy","Footprints in Time interpretive walk along the Little Bonnechere River",1),
  ("mikisew","The Point Trail",0.3,"Easy","A narrow point jutting into Eagle Lake, perfect picnic spot",1),
  ("mikisew","Narrows Trail",1.8,"Easy","Walk or bike from the campground to the Eagle Lake Narrows country store",2),
  ("rondeau","Warbler's Way",0.5,"Easy","The park's shortest loop, big during spring migration",1),
  ("rondeau","Tulip Tree Trail",1.2,"Easy","Accessible boardwalk through mature Carolinian forest, Prothonotary Warbler territory",2),
  ("rondeau","Black Oak Trail",1.4,"Easy","Pine-oak savanna with Wood Lily and Woodland Sunflower meadows",3),
  ("rondeau","Spicebush Trail",1.5,"Easy","Old-growth tulip trees, beech, and a spring wildflower carpet",4),
  ("rondeau","Marsh Trail",7.2,"Easy","One-way along Rondeau Bay through the big wetland; bring bug spray",5),
  ("rondeau","South Point Trail",8.0,"Easy","Forest walk to the quiet south tip of the peninsula",6),
  ("rondeau","Harrison Trail",16.0,"Easy","The multi-use spine of the park through oak woodland; bike-friendly",7),
  ("neys","Point Trail",1.0,"Easy","Shoreline walk from Prisoners Cove to Prisoners Point",1),
  ("neys","Under the Volcano",1.0,"Moderate","Volcanic rock formations beyond Prisoners Point",2),
  ("neys","Dune Trail",1.3,"Easy","Loop through the fragile dune ecosystem behind the beach",3),
  ("neys","Lookout Trail",1.6,"Moderate","Climbs above Area 4 for views over Ashburton Bay",4),
  ("neys","Kopa Cove Trail",2.0,"Moderate","Linear route to a rugged cobble cove",5),
  ("neys","Pic Island Overlook",4.0,"Difficult","To the view of Pic Island that Lawren Harris painted",6),
  ("chutes","Twin Bridges Trail",6.0,"Moderate","Falls, the Seven Sisters rapids, and river lookouts; short out-and-back option to the bridges",1),
  ("fairbank","Wa-Shai-Ga-Mog Trail",0.5,"Moderate","Bedrock climb to views of Fairbank Lake and the Fairbank Fault",1),
]

def labels_for(spec):
    if spec[0] == "range":
        return [str(n) for n in range(spec[1], spec[2] + 1)]
    return list(spec[1])

def main():
    if os.path.exists(DB): os.remove(DB)
    con = sqlite3.connect(DB)
    con.executescript(open("schema.sql").read())
    cur = con.cursor()
    for pid, p in PARKS.items():
        cur.execute("INSERT INTO parks(id,name,region,url,blurb,fishing,fmz,sort,facilities) VALUES(?,?,?,?,?,?,?,?,?)",
            (pid, p["name"], p["region"], p["url"], p["blurb"], p["fishing"], p["fmz"], p["sort"], json.dumps(p["facilities"])))
    total = 0
    for (pid, name, sub, sort, spec) in CAMPGROUNDS:
        cur.execute("INSERT INTO campgrounds(park_id,name,sub,sort) VALUES(?,?,?,?)", (pid, name, sub, sort))
        cg_id = cur.lastrowid
        rows = [(cg_id, lbl, 0, SRC) for lbl in labels_for(spec)]
        cur.executemany("INSERT INTO sites(campground_id,label,verified,source) VALUES(?,?,?,?)", rows)
        total += len(rows)
    for (pid, tname, length, diff, detail, tsort) in TRAILS:
        cur.execute("INSERT INTO trails(park_id,name,length_km,difficulty,detail,sort) VALUES(?,?,?,?,?,?)",
                    (pid, tname, length, diff, detail, tsort))
    con.commit()
    print(f"Built {DB}: {len(PARKS)} parks, {len(CAMPGROUNDS)} campgrounds, {total} sites, {len(TRAILS)} trails\n")
    for pid, name, sort in cur.execute("SELECT id,name,sort FROM parks ORDER BY sort").fetchall():
        n = con.execute("SELECT COUNT(*) FROM sites s JOIN campgrounds c ON s.campground_id=c.id WHERE c.park_id=?",(pid,)).fetchone()[0]
        print(f"  {sort:>3}  {name:16} {n:>5} sites")
    con.close()

if __name__ == "__main__":
    main()
